---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=curl state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      shell: curl -sSL https://get.docker.com/ | sh 
      register: result

    - debug:
       var=result

    - name: Add group docker to user guest
      user:
        name: guest
        groups: docker
        append: yes

