---

all:
  hosts:
    frontend_machine_1:
      ansible_ssh_host:  "localhost"
      ansible_ssh_user:  "guest"
      ansible_ssh_pass:  "guest"
      ansible_sudo_pass:  "guest"
      ansible_python_interpreter: "/usr/bin/python3"
  
    frontend_machine_2:
      ansible_ssh_host:  "localhost"
      ansible_ssh_user:  "guest2"
      ansible_ssh_pass:  "guest2"
      ansible_sudo_pass:  "guest"
      ansible_python_interpreter: "/usr/bin/python3"


    frontend_machine_3:
      ansible_ssh_host:  "localhost"
      ansible_ssh_user:  "guest3"
      ansible_ssh_pass:  "guest3"
      ansible_sudo_pass:  "guest3"
      ansible_python_interpreter: "/usr/bin/python3"
